export const SET_TOKEN = 'SET_TOKEN';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_TOKEN_ERROR = 'SET_TOKEN_ERROR';

export const SET_ME = 'SET_ME';
export const SET_ME_SUCCESS = 'SET_ME_SUCCESS';
export const SET_ME_ERROR = 'SET_ME_ERROR';

export const ADD_LIST_PHOTOS = 'ADD_LIST_PHOTOS';
export const ADD_LIST_PHOTOS_SUCCESS = 'ADD_LIST_PHOTOS_SUCCESS';
export const ADD_LIST_PHOTOS_ERROR = 'ADD_LIST_PHOTOS_ERROR';

export const LIKE_PHOTO = 'LIKE_PHOTO';
export const LIKE_PHOTO_SUCCESS = 'LIKE_PHOTO_SUCCESS';
export const LIKE_PHOTO_ERROR = 'LIKE_PHOTO_ERROR';

export const UNLIKE_PHOTO = 'UNLIKE_PHOTO';
export const UNLIKE_PHOTO_SUCCESS = 'UNLIKE_PHOTO_SUCCESS';
export const UNLIKE_PHOTO_ERROR = 'UNLIKE_PHOTO_ERROR';